"""
Generate a small, schema-valid SYNTHETIC per-unit export fixture for demo / CI.

Emits the twelve-column per-unit export the WEVM layer consumes:
    country, year, unit_id, scenario, net_income, income, survey_weight,
    household_type, is_working_age, n_adults, n_children, region
with a baseline and two reform scenarios.

ALL VALUES ARE SYNTHETIC — generated directly here, with no PolicyEngine and no
FRS data, so the fixture can be committed and the CI schema guard can run without
safeguarded data or the full pipeline. This is deliberately distinct from
generate_demo_data.py (which fabricates raw FRS inputs for the full demo
pipeline): the committed export fixture must be static synthetic data, so it is
produced directly rather than by running the engine.

Output:
    uk/model/demo/per_unit_export.parquet
    uk/model/demo/SYNTHETIC_FIXTURE_WARNING.txt
"""
from pathlib import Path

import numpy as np
import pandas as pd

SEED = 20240
N_UNITS = 200
COUNTRY = "GB"
YEAR = 2023  # FRS 2023-24 survey-start year (single-wave scope)

# PolicyEngine region enum keys (the REGION_MAP values) — the export's region
# convention, matching what the real pipeline emits.
REGIONS = [
    "NORTH_EAST", "NORTH_WEST", "YORKSHIRE", "EAST_MIDLANDS", "WEST_MIDLANDS",
    "EAST_OF_ENGLAND", "LONDON", "SOUTH_EAST", "SOUTH_WEST",
    "SCOTLAND", "WALES", "NORTHERN_IRELAND",
]

COLUMNS = [
    "country", "year", "unit_id", "scenario", "net_income", "income",
    "survey_weight", "household_type", "is_working_age", "n_adults",
    "n_children", "region",
]


def _household_type(n_adults: int, n_children: int) -> str:
    if n_adults == 1 and n_children == 0:
        return "Single, no children"
    if n_adults == 1:
        return "Single, with children"
    if n_children == 0:
        return "Couple, no children"
    return "Couple with children"


def generate(seed: int = SEED, n: int = N_UNITS) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    n_adults = rng.integers(1, 3, n)
    n_children = rng.integers(0, 4, n)
    region = rng.choice(REGIONS, n)
    weight = rng.uniform(600, 1800, n).round(1)
    base_net = rng.lognormal(10.0, 0.55, n)                       # baseline disposable income
    market = (base_net * rng.uniform(1.05, 1.7, n)).round(2)      # market income
    htype = [_household_type(int(a), int(c)) for a, c in zip(n_adults, n_children)]
    uid = [f"{COUNTRY}_{YEAR}_{i:05d}" for i in range(n)]

    # baseline + two reforms (one progressive, one roughly proportional).
    scenarios = {
        "baseline": base_net,
        "uc_uplift": base_net + np.maximum(0.0, 18000.0 - base_net) * 0.04,
        "ni_cut": base_net + base_net * 0.012,
    }

    frames = []
    for scenario, net in scenarios.items():
        frames.append(pd.DataFrame({
            "country": COUNTRY,
            "year": YEAR,
            "unit_id": uid,
            "scenario": scenario,
            "net_income": np.round(net, 2),
            "income": market,
            "survey_weight": weight,
            "household_type": htype,
            "is_working_age": True,
            "n_adults": n_adults,
            "n_children": n_children,
            "region": region,
        }))
    return pd.concat(frames, ignore_index=True)[COLUMNS]


def main() -> None:
    out_dir = Path(__file__).resolve().parent            # uk/model/demo/
    df = generate()
    out_path = out_dir / "per_unit_export.parquet"
    df.to_parquet(out_path, index=False)
    (out_dir / "SYNTHETIC_FIXTURE_WARNING.txt").write_text(
        "uk/model/demo/per_unit_export.parquet is SYNTHETIC.\n"
        "Generated by uk/model/demo/generate_synthetic_export.py for the CI schema\n"
        "guard and demo use only. No FRS or PolicyEngine data is involved.\n"
        "Do NOT use for policy analysis or publication.\n"
    )
    print(f"wrote {out_path}")
    print(f"rows={len(df)}  scenarios={sorted(df['scenario'].unique())}")
    print("columns:", list(df.columns))


if __name__ == "__main__":
    main()
