#!/usr/bin/env bash
# run_pipeline.sh — run the full FRS pipeline for the FRS 2023-24 survey year.
#
# Usage (from project root):
#   bash run_pipeline.sh            # full pipeline — requires real FRS parquets in inputs/
#   bash run_pipeline.sh --demo     # demo mode — generates synthetic data, runs the pipeline
#
# Steps 02-07 are run for FRS 2023-24 (full mode).
# Step 01 (PostgreSQL extract) is skipped — FRS microdata is UKDS safeguarded
# and is NOT committed to the repo. Obtain the FRS parquet extracts from UKDS
# (https://ukdataservice.ac.uk) and place them in inputs/ before running.
# All steps run sequentially — HDF5 file locking on macOS prevents parallel reads.
#
# Requirements: Python 3.11 venv at venv/ (pip install -r requirements.txt)

set -euo pipefail

DEMO_MODE=false
for arg in "$@"; do
    [ "$arg" = "--demo" ] && DEMO_MODE=true
done

ROOT="$(cd "$(dirname "$0")" && pwd)"
VENV="$ROOT/venv/bin/activate"

if [ ! -f "$VENV" ]; then
    echo "ERROR: venv not found at $ROOT/venv/"
    echo "Run: python3.11 -m venv venv && source venv/bin/activate && pip install -r requirements.txt"
    exit 1
fi

# shellcheck disable=SC1090
source "$VENV"

run_year() {
    local YEAR="$1"   # e.g. 23_24
    local DIR="model/Code_FRS_${YEAR}"

    echo ""
    echo "========================================================"
    echo "  FRS ${YEAR} — starting pipeline"
    echo "========================================================"

    echo "[${YEAR}] Step 02 — build benefit-unit table"
    python "${DIR}/02_build_benefit_unit_table.py"

    echo "[${YEAR}] Step 03 — build PolicyEngine dataset"
    python "${DIR}/03_build_policyengine_dataset.py"

    echo "[${YEAR}] Step 04 — baseline"
    python "${DIR}/04_run_frs_baseline.py"

    echo "[${YEAR}] Step 05 — reforms"
    python "${DIR}/05_run_frs_reforms.py"

    echo "[${YEAR}] Step 06 — shocks"
    python "${DIR}/06_run_frs_shocks.py"

    echo "[${YEAR}] Step 07 — combined scenarios + per-unit export"
    python "${DIR}/07_run_frs_combined_scenarios.py"

    echo "[${YEAR}] Done."
}

cd "$ROOT"

run_year_demo() {
    local YEAR="$1"
    local DIR="model/Code_FRS_${YEAR}"

    echo ""
    echo "========================================================"
    echo "  FRS ${YEAR} — starting pipeline (demo)"
    echo "========================================================"
    echo "[${YEAR}] Step 02 — build benefit-unit table"
    python "${DIR}/02_build_benefit_unit_table.py"
    echo "[${YEAR}] Step 03 — build PolicyEngine dataset"
    python "${DIR}/03_build_policyengine_dataset.py"
    # Steps 04-06 run sequentially in demo mode — HDF5 file locking on macOS
    echo "[${YEAR}] Step 04 — baseline"
    python "${DIR}/04_run_frs_baseline.py"
    echo "[${YEAR}] Step 05 — reforms"
    python "${DIR}/05_run_frs_reforms.py"
    echo "[${YEAR}] Step 06 — shocks"
    python "${DIR}/06_run_frs_shocks.py"
    echo "[${YEAR}] Step 07 — combined scenarios + per-unit export"
    python "${DIR}/07_run_frs_combined_scenarios.py"

    mkdir -p "$ROOT/demo/outputs/frs_${YEAR}"
    cat > "$ROOT/demo/outputs/frs_${YEAR}/SYNTHETIC_OUTPUTS_WARNING.txt" <<'MSG'
ALL OUTPUTS IN THIS DIRECTORY ARE DERIVED FROM SYNTHETIC DATA.
Generated by bash run_pipeline.sh --demo — for pipeline testing only.
Do NOT use for policy analysis or publication.
MSG
    echo "[${YEAR}] Done."
}

if [ "$DEMO_MODE" = true ]; then
    export FRS_DEMO_MODE=1
    echo ""
    echo "========================================================"
    echo "  DEMO MODE — synthetic data only"
    echo "  All outputs are labelled SYNTHETIC and must not be"
    echo "  used for policy analysis or publication."
    echo "========================================================"
    echo ""
    mkdir -p "$ROOT/demo/inputs/frs_2023_24"
    mkdir -p "$ROOT/demo/processed/frs_2023_24"
    mkdir -p "$ROOT/demo/outputs/frs_2023_24"

    echo "[demo] Generating synthetic FRS parquets..."
    python model/demo/generate_demo_data.py

    run_year_demo "23_24"

    echo ""
    echo "========================================================"
    echo "  Demo complete. Synthetic outputs in:"
    echo "    demo/outputs/frs_2023_24/"
    echo "  Step 08 (Excel tool) skipped — requires DB access."
    echo "========================================================"
else
    run_year "23_24"

    echo ""
    echo "========================================================"
    echo "  Pipeline complete."
    echo "  Outputs:"
    echo "    outputs/frs_2023_24/per_unit_export.parquet"
    echo "========================================================"
fi
