"""
convert_el.py -- FULL EL 2024 EU-SILC data -> EUROMOD input conversion.

Greek analogue of the validated ES converter (es_real/convert_full.py), following
the EL Data Requirements Document (DRD_EL_training_data.xls) and the EL model spine
(income lists extracted from EL.xml). Runs on system EL_2023 with dataset
EL_2024_c1_2015_03_e2 (yearCollection 2024, income year 2023), the EL analogue of
ES_2024_b1_2015_03_e2.

EL-SPECIFIC STRUCTURES (differ from ES), each established at EL-0:
  1. EARNINGS SPLIT. The EL income list is ils_earns = yemre + ysere + yemnr + ysenr
     (reported + non-reported, the tax-evasion module), NOT yem/yse. The training
     data confirms the input convention: yem == yemre (mirrored), yse == 0 while
     ysere carries self-employment. So we feed yemre (and mirror yem) and ysere,
     leaving yse/yemnr/ysenr = 0. Total earnings (hence market income, a welfare
     aggregate) is preserved regardless of how the model later splits reported vs
     non-reported, so the welfare gate is robust to this.
  2. PENSION ROUTING. ils_pen reads poa00 + poacm + poaot + psuor + psuwd + pdi
     (READ components; boanc_s social pension is simulated). Route the SILC
     pension aggregates into the contributory read components the list actually
     sums: PY100G -> poa00 (main old age), PY110G -> psuwd (survivors'),
     PY130G -> pdi (disability). The synthetic base populated only poa00, so
     survivor and disability pensions were absent there; the real build supplies
     them. poacm/poaot/psuor stay 0 (the EU-SILC data cannot separate supplementary,
     minor, and orphan pensions; documented disaggregation limit).
  3. NET-TO-GROSS. EL gross (PY...G) is NSI-derived (ELSTAT converts net<->gross,
     Eurostat KS-TC-20-001), not directly measured. We do NOT take it on trust: a
     consistency pass checks gross >= net at the component level and reconciles by
     imputing gross from the population gross/net ratio where the held gross is
     missing or below net (per the EMC net-to-gross convention). The diagnostics
     are logged; the reconciliation is bounded and recorded.
  4. REGION. EL has no NUTS region in the EUROMOD input template; it uses the
     degree-of-urbanisation triplet drgur/drgru/drgmd (from SILC DB100). The NUTS-1
     code (DB040) is carried separately into the per-unit layer (build_el.py) for
     the RWI join, since it is not a EUROMOD input variable.

2026-08-02, COMPLETED CONVERSION. Every input variable a live EL_2023 policy reads for
which the codebook publishes a recipe, and whose sources the public user database carries,
is now populated. The inventory is generated by `europe/model/input_inventory.py`. The
consequential one is `tpr`: the Greek property tax is `hy120g/12`, HY120G is present for
8,712 households, and the live 2023 branch of `tpr_el` computes `tpr_s = tpr - i_tpr_red`
with the reduction applying only to income years before 2019. So the read input passes
through as the simulated ENFIA, and residual EL-4 (property tax simulated at zero against
an external 1,575m) closes. Greece's remaining gaps are the national-SILC benefit
components (kb02_*, eu02_*, sb02_*, oe02_*), the pension-fund and hazardous-work variables
(em03, em06), the property area sk02_2, and drgn2, for which the release carries NUTS-1
only.

ACCURACY CEILING (the EU-SILC data lacks national-SILC and employment-history
variables): contributory unemployment (bunct_s), the minimum-income KEA (bsa00_s),
child benefit A21 (bch_s), large-family (bfalg_s) and housing-related minimum
benefits are SIMULATED by the model from drivers the UDB only partly carries, so
they come out as the model computes, not as the survey recorded. The contribution
base and the Heckman wage are proxied. Each is logged. Read benefits the model does
not separately simulate (sickness bhl, education bed, housing bho) are fed from
their SILC sources.

DATA HANDLING: reads the EU-SILC data read-only; never writes converted microdata
to disk; returns the input DataFrame in memory for a single .run().
"""
import glob
import os

import numpy as np
import pandas as pd

# The licensed EU-SILC UDB. Held outside this tree, and outside the sibling
# LOCAL_ONLY, under the IGP data share. Set BENEFITS_SILC_ROOT to the folder holding the
# per-country _CROSS directories to run this anywhere else; the literal below is where it
# sits on the machine the surfaces were built on, kept as the recorded location rather
# than as an assumption about any other machine.
_SILC_ROOT = os.environ.get(
    "BENEFITS_SILC_ROOT",
    "")
UDB = os.path.join(_SILC_ROOT, "EL_CROSS", "2024")
if not os.path.isdir(UDB):
    raise SystemExit(
        "EU-SILC UDB not found at:\n  " + UDB + "\n"
        "Set BENEFITS_SILC_ROOT to the folder containing EL_CROSS/2024, which must hold\n"
        "UDB_cEL24D.csv, UDB_cEL24H.csv, UDB_cEL24P.csv and UDB_cEL24R.csv.\n"
        "The data is licensed and is not, and must not be, in this repository.")
MONTH = 1.0 / 12.0
# SILC PL032 (self-defined economic status) for the non-employed -> EUROMOD les
#   1 employee, 2 unemployed, 3 retired, 4 unable/disabled, 5 other inactive ...
# EUROMOD les: 2 self-employed, 3 employee, 5 unemployed, 6 retired/pension,
#   7 inactive/other, 4 sick/disabled, 1 in education.
PL032_NONEMP = {2: 5, 3: 6, 4: 4, 5: 7, 6: 7, 7: 7, 8: 4, 9: 1}
PB190_TO_DMS = {1: 1, 2: 2, 3: 3, 4: 5, 5: 4}   # SILC marital -> EUROMOD dms (4=div,5=wid)
# SILC HH021 tenure -> EUROMOD amrtn (1 owned outright, 2 owner w/ mortgage,
#   3 tenant market rent, 4 reduced/free)
HH021_TO_AMRTN = {1: 1, 2: 2, 3: 3, 4: 3, 5: 4}
# ISCO-08 two-digit (PL051A) -> EUROMOD loc, the codebook's EL recipe, transcribed.
LOC_BANDS = [((1, 2, 3), 0), (range(11, 15), 1), (range(21, 27), 2), (range(31, 36), 3),
             (range(41, 45), 4), (range(51, 55), 5), (range(61, 64), 6),
             (range(71, 76), 7), (range(81, 84), 8), (range(91, 97), 9)]
# The rate the EL codebook's own afc recipe divides by, stated once and consistently.
EL_INT_RATE = 0.00302

LOG = []


def _file(letter):
    return glob.glob(os.path.join(UDB, f"UDB_c*{letter}.csv"))[0]


def _deh(pe041):
    """SILC PE041 (ISCED highest attained) -> EUROMOD deh 1/2/3 (low/medium/high)."""
    v = pd.to_numeric(pe041, errors="coerce")
    out = np.where(v >= 500, 3, np.where(v >= 300, 2, 1)).astype("int64")
    out[np.isnan(v)] = 1
    return out


def _degurba(db100):
    """SILC DB100 (degree of urbanisation: 1 dense, 2 intermediate, 3 thin)."""
    v = pd.to_numeric(db100, errors="coerce").fillna(1).to_numpy()
    drgur = (v == 1).astype("int64")
    drgmd = (v == 2).astype("int64")
    drgru = (v == 3).astype("int64")
    # default to urban where unknown
    drgur[~np.isin(v, [1, 2, 3])] = 1
    return drgur, drgmd, drgru


def _loc(pl051a, has_earnings):
    """EUROMOD loc from ISCO-08 two-digit PL051A, the codebook's EL recipe.

    The Greek recipe has no imputation clause, unlike the Spanish one, so missing stays
    missing and is carried as the recipe's own -1 where the person has no earnings, and as
    0 (not applicable) otherwise. No live Greek policy reads loc; it is supplied because
    the codebook publishes it and because it is the input to the lochz fallback rule.
    """
    v = pd.to_numeric(pl051a, errors="coerce").to_numpy()
    out = np.full(len(v), np.nan)
    for codes, val in LOC_BANDS:
        out[np.isin(v, list(codes))] = val
    out[np.isnan(out) & ~has_earnings] = -1
    out[np.isnan(out)] = 0
    return out.astype("int64")


def _dec(pe021, pe010):
    """EUROMOD dec from the codebook's EL recipe: pe021 recoded, then 0 if pe010 == 2."""
    e21 = pd.to_numeric(pe021, errors="coerce").to_numpy()
    e10 = pd.to_numeric(pe010, errors="coerce").to_numpy()
    d = np.full(len(e21), np.nan)
    d[e21 == 10] = 2
    d[e21 == 20] = 3
    d[(e21 >= 30) & (e21 <= 39)] = 4
    d[(e21 >= 40) & (e21 <= 49)] = 5
    d[(e21 >= 50) & (e21 <= 80)] = 6
    d[e10 == 2] = 0
    d[np.isnan(d)] = 0
    return d.astype("int64")


def _reconcile_gross(P, log):
    """Net-to-gross internal-consistency pass on the NSI-derived gross. For each
    income component with both gross (G) and net (N) forms, where gross is missing
    or below net but net is positive, impute gross from the population median G/N
    ratio. Returns a dict of reconciled gross Series and logs the diagnostics."""
    comps = {"PY010G": "PY010N", "PY050G": "PY050N", "PY090G": "PY090N",
             "PY100G": "PY100N", "PY110G": "PY110N", "PY120G": "PY120N",
             "PY130G": "PY130N", "PY140G": "PY140N"}
    out = {}
    for g, n in comps.items():
        gs = pd.to_numeric(P.get(g, 0), errors="coerce").fillna(0.0)
        if n not in P.columns:
            out[g] = gs
            continue
        ns = pd.to_numeric(P[n], errors="coerce").fillna(0.0)
        both = (gs > 0) & (ns > 0)
        ratio = float((gs[both].sum() / ns[both].sum())) if both.sum() else 1.0
        ratio = min(max(ratio, 1.0), 1.8)  # gross >= net, bounded
        # records where net is present but gross is missing/below net
        bad = (ns > 0) & (gs < ns)
        nbad = int(bad.sum())
        fixed = gs.copy()
        fixed[bad] = ns[bad] * ratio
        out[g] = fixed
        if nbad:
            log.append(f"net-to-gross {g}: G/N ratio={ratio:.3f}; {nbad} records had "
                       f"gross<net, imputed gross = net*ratio")
        else:
            log.append(f"net-to-gross {g}: G/N ratio={ratio:.3f}; gross internally "
                       f"consistent (no gross<net), used as held")
    return out


def convert_el_2024_full(template_cols):
    LOG.clear()
    tset = set(template_cols)

    def setcol(out, name, values):
        if name in tset:
            out[name] = values

    D = pd.read_csv(_file("D"), usecols=["DB030", "DB090", "DB040", "DB100"])
    R = pd.read_csv(_file("R"), usecols=["RB030", "RX030", "RX020", "RB090",
                                         "RB220", "RB230", "RB240"])
    pcols = ["PB030", "PB190", "PE010", "PE021", "PE041", "PL032", "PL040A", "PL051A",
             "PL060", "PL073", "PL074", "PL075", "PL076", "PL200", "PL085",
             "PY010G", "PY010N", "PY020G", "PY035G", "PY050G", "PY050N", "PY080G",
             "PY090G", "PY090N", "PY100G", "PY100N", "PY110G", "PY110N",
             "PY120G", "PY120N", "PY130G", "PY130N", "PY140G", "PY140N"]
    Phead = pd.read_csv(_file("P"), nrows=0).columns
    P = pd.read_csv(_file("P"), usecols=[c for c in pcols if c in Phead])
    H = pd.read_csv(_file("H"), usecols=["HB030", "HX010", "HY020", "HY040G", "HY050G",
                                         "HY060G", "HY070G", "HY080G", "HY090G",
                                         "HY100G", "HY110G", "HY120G", "HY130G",
                                         "HY131G", "HY140G", "HY145N",
                                         "HH021", "HH060", "HH070"])

    # net-to-gross reconciliation (component-level), keyed to person rows
    grossP = _reconcile_gross(P, LOG)

    df = R.rename(columns={"RB030": "idperson", "RX030": "idhh",
                           "RX020": "dag", "RB090": "sex"})
    df = df.merge(D.rename(columns={"DB030": "idhh", "DB090": "dwt",
                                    "DB040": "nuts1", "DB100": "degurba"}),
                  on="idhh", how="left")
    df = df.merge(P.rename(columns={"PB030": "idperson"}), on="idperson", how="left")
    # attach reconciled gross by mapping on person id (P is 1 row per person)
    pmap = P.assign(**{g + "_rec": v for g, v in grossP.items()}).set_index("PB030")
    for g in grossP:
        df[g + "_rec"] = df["idperson"].map(pmap[g + "_rec"]).fillna(0.0).to_numpy()

    n = len(df)
    df = df.merge(H.rename(columns={"HB030": "idhh"}), on="idhh", how="left")

    # household amounts (capital, rent, transfers, household benefits) -> OLDEST
    # member of each household (EMC sharing rule), exactly one recipient.
    oldest = df.groupby("idhh")["dag"].transform("max")
    first_oldest = df.assign(_o=(df["dag"] == oldest)).sort_values(
        ["idhh", "_o", "idperson"], ascending=[True, False, True])
    recip = first_oldest.groupby("idhh").head(1).index
    is_recip = np.zeros(n, dtype=bool)
    is_recip[df.index.get_indexer(recip)] = True
    #
    # ALLOCATION SUBSTITUTION, stated once. The codebook allocates household money to "the
    # default income recipients", or for housing costs to the people responsible for the
    # accommodation. The public release identifies neither (HB080 and HB090 are not in it),
    # so the whole household amount goes to the oldest member, the EMC sharing rule already
    # used here. Household totals are exact; only the within-household allocation differs.
    # HY110G is the exception and is NOT allocated here: its own recipe splits it between
    # the household's members under 16.
    hh_money = ["HY040G", "HY050G", "HY060G", "HY070G", "HY080G", "HY090G",
                "HY100G", "HY120G", "HY130G", "HY131G", "HY140G", "HY145N", "HY020",
                "HH060", "HH070"]
    for c in hh_money:
        df[c] = np.where(is_recip, pd.to_numeric(df[c], errors="coerce").fillna(0.0), 0.0)
    LOG.append("household amounts allocated to the oldest member (EMC): "
               + ", ".join(hh_money))

    out = pd.DataFrame(0.0, index=np.arange(n), columns=list(template_cols))

    # ---- identifiers and pointers ----
    setcol(out, "idperson", df["idperson"].to_numpy("int64"))
    setcol(out, "idhh", df["idhh"].to_numpy("int64"))
    for src, dst in (("RB220", "idfather"), ("RB230", "idmother"), ("RB240", "idpartner")):
        v = pd.to_numeric(df[src], errors="coerce").fillna(0)
        setcol(out, dst, np.where(v > 0, v, 0).astype("int64"))
    LOG.append("pointers idfather/idmother/idpartner <- RB220/RB230/RB240 (full ids)")

    # ---- demographics ----
    setcol(out, "dag", df["dag"].fillna(0).clip(lower=0).to_numpy("int64"))
    setcol(out, "dgn", np.where(df["sex"].to_numpy() == 1, 1, 0))
    dms = df["PB190"].map(PB190_TO_DMS)
    setcol(out, "dms", dms.where(df["dag"] >= 16, 1).fillna(1).to_numpy("int64"))
    setcol(out, "ddi", (df["PY130G_rec"].fillna(0) > 0).astype("int64").to_numpy())
    setcol(out, "deh", _deh(df["PE041"]))
    drgur, drgmd, drgru = _degurba(df["degurba"])
    setcol(out, "drgur", drgur)
    setcol(out, "drgmd", drgmd)
    setcol(out, "drgru", drgru)
    amrtn = df["HH021"].map(HH021_TO_AMRTN)
    setcol(out, "amrtn", amrtn.fillna(3).to_numpy("int64"))
    setcol(out, "dwt", df["dwt"].fillna(0.0).to_numpy())
    LOG.append("dms<-PB190; ddi<-(PY130G>0); deh<-PE041(ISCED); drgur/md/ru<-DB100; "
               "amrtn<-HH021; dwt<-DB090 (household-constant)")

    # ---- labour ----
    adult = (df["dag"] >= 16).to_numpy()
    pl040 = df["PL040A"]
    les = np.zeros(n, dtype="int64")
    les[adult & pl040.isin([1, 2, 4]).to_numpy()] = 2     # self-employed/family worker
    les[adult & (pl040 == 3).to_numpy()] = 3              # employee
    nonemp = adult & (les == 0)
    inferred = df["PL032"].map(PL032_NONEMP).fillna(7).to_numpy().astype("int64")
    les[nonemp] = inferred[nonemp]
    setcol(out, "les", les)
    lhw = pd.to_numeric(df["PL060"], errors="coerce").fillna(0).to_numpy(float)
    lhw = np.where((les == 3) & (lhw <= 0), 38.0, lhw)
    setcol(out, "lhw", lhw)
    months_work = df[["PL073", "PL074", "PL075", "PL076"]].apply(
        pd.to_numeric, errors="coerce").fillna(0).sum(axis=1).clip(0, 12)
    setcol(out, "liwmy", months_work.to_numpy())
    setcol(out, "liwwh", (pd.to_numeric(df["PL200"], errors="coerce").fillna(0) * 12)
           .clip(lower=0).to_numpy())
    setcol(out, "lunmy", pd.to_numeric(df["PL085"], errors="coerce").fillna(0)
           .clip(0, 12).to_numpy())
    # social-insurance fund (lpmfc): employees -> IKA main private-sector fund (1),
    # which the employee-SIC simulation requires (lpmfc 0 is the self-employed/other
    # group, under which NO employee SIC fires); self-employed -> self-employed fund
    # (2). The UDB cannot identify the specific fund (civil-servant 7, banking 5,
    # public-enterprise 4), so all employees are assigned IKA, the dominant fund;
    # the uprating factors for the income year are ~1.0 so this does not move
    # earnings. Documented contribution-fund approximation.
    lpmfc = np.zeros(n, dtype="int64")
    lpmfc[les == 3] = 1
    lpmfc[les == 2] = 2
    setcol(out, "lpmfc", lpmfc)
    LOG.append("les<-PL040A/PL032; lhw<-PL060(def38 emp); liwmy<-sum(PL073..076); "
               "liwwh<-PL200*12; lunmy<-PL085; lpmfc=1(emp IKA)/2(self-emp) for SIC "
               "(lpm regime proxy tested, no effect on SIC level, left at default)")

    # ---- market incomes (gross, monthly): EL earnings split convention ----
    yem = df["PY010G_rec"].fillna(0.0).to_numpy() * MONTH
    yse = df["PY050G_rec"].fillna(0.0).to_numpy() * MONTH
    setcol(out, "yem", yem)            # gross employment; model derives yemre/yemnr
    setcol(out, "yemre", yem)          # mirror reported (model preserves on no-evasion)
    setcol(out, "yse", yse)            # gross self-employment; model derives ysere/ysenr
    setcol(out, "ysere", yse)          # mirror (model OVERWRITES this from yse)
    # yemnr, ysenr left 0 (the model splits the gross into reported/non-reported)
    setcol(out, "ypp", df["PY080G"].fillna(0.0).to_numpy() * MONTH)   # private pension
    setcol(out, "yiy", df["HY090G"].fillna(0.0).to_numpy() * MONTH)   # investment (oldest)
    setcol(out, "ypr", df["HY040G"].fillna(0.0).to_numpy() * MONTH)   # rent (oldest)
    setcol(out, "ypt", df["HY080G"].fillna(0.0).to_numpy() * MONTH)   # inter-hh transfers in
    # xmpam and xmpot are set in the block below, decomposed on HY131G.
    LOG.append("earnings: yem=yemre<-PY010G, yse=ysere<-PY050G (/12); model splits the "
               "gross into reported/non-reported (yemnr/ysenr); feeding yse is required "
               "(the under-reporting policy re-derives ysere from yse, so yse=0 wiped it); "
               "ypp<-PY080G, yiy<-HY090G, ypr<-HY040G, ypt<-HY080G")

    # ---- pensions (gross, monthly): route to the income-list READ components ----
    oldage = df["PY100G_rec"].fillna(0.0).to_numpy() * MONTH
    surv = df["PY110G_rec"].fillna(0.0).to_numpy() * MONTH
    disab = df["PY130G_rec"].fillna(0.0).to_numpy() * MONTH
    setcol(out, "poa00", oldage)       # main old age <- PY100G
    setcol(out, "psuwd", surv)         # survivors' <- PY110G (absent in synthetic base)
    setcol(out, "pdi", disab)          # disability <- PY130G (absent in synthetic base)
    # poacm/poaot/psuor stay 0: UDB cannot separate supplementary/minor/orphan pensions
    LOG.append("pensions: poa00<-PY100G, psuwd<-PY110G [survivor, absent in synthetic], "
               "pdi<-PY130G [disability]; poacm/poaot/psuor=0 (UDB cannot separate)")

    # ---- read benefits the model does not separately simulate ----
    setcol(out, "bhl", df["PY120G_rec"].fillna(0.0).to_numpy() * MONTH)   # sickness
    setcol(out, "bed", df["PY140G_rec"].fillna(0.0).to_numpy() * MONTH)   # education
    setcol(out, "bho", df["HY070G"].fillna(0.0).to_numpy() * MONTH)       # housing (read)
    LOG.append("read benefits: bhl<-PY120G (sickness), bed<-PY140G (education), "
               "bho<-HY070G (housing, the active read component in ils_benmt)")

    # ---- unemployment: contributory is SIMULATED (bunct_s); feed the driver ----
    unemp = df["PY090G_rec"].fillna(0.0).to_numpy() * MONTH
    setcol(out, "bunct", unemp)        # read driver; income list uses simulated bunct_s
    LOG.append("CEILING: contributory unemployment is simulated (bunct_s) from "
               "contribution/duration history the UDB lacks; bunct<-PY090G fed as driver")
    LOG.append("LEFT TO SIMULATION (input 0): KEA minimum income (bsa00_s), child "
               "benefit A21 (bch_s), large-family (bfalg_s), social pension (boanc_s); "
               "family/social-exclusion SILC aggregates (HY050/060G) not fed to read "
               "components to avoid double-counting the simulated means-tested benefits")

    # ---- months-receiving and proxies (accuracy ceiling) ----
    # ---- The rest of what the codebook publishes and the release carries ----
    # tpr is the consequential one. tpr = hy120g/12*hx010, and the live 2023 branch of
    # tpr_el sets tpr_s = tpr - i_tpr_red with the reduction gated on income years before
    # 2019, so this read input IS the simulated ENFIA for 2023.
    setcol(out, "tpr", df["HY120G"].to_numpy() * MONTH)
    # yot = hy110g/12*hx010 shared equally between the people aged under 16 (codebook rule)
    child = (df["dag"].fillna(0) < 16).to_numpy()
    totchild = pd.Series(child.astype(float)).groupby(df["idhh"].to_numpy()).transform("sum")
    hy110 = pd.to_numeric(df["HY110G"], errors="coerce").fillna(0.0).to_numpy()
    setcol(out, "yot", np.where(child & (totchild.to_numpy() > 0),
                                hy110 / np.maximum(totchild.to_numpy(), 1.0) * MONTH, 0.0))
    # housing costs. HH060 and HH070 are held monthly in SILC, so they are used as held;
    # HY100G is annual and is divided.
    xhcrt = df["HH060"].to_numpy()
    xhcmomi = df["HY100G"].to_numpy() * MONTH
    xhc = df["HH070"].to_numpy()
    setcol(out, "xhcrt", xhcrt)
    setcol(out, "xhcmomi", xhcmomi)
    setcol(out, "xhc", xhc)
    setcol(out, "xhcot", np.maximum(xhc - xhcrt - xhcmomi, 0.0))
    # maintenance paid, decomposed: xmpam is the alimony component hy131g, xmpot the rest.
    # Until now the whole of HY130G was routed into xmpam. ils_origy subtracts both, so the
    # household total is unchanged and only the split is corrected.
    xmpam = df["HY131G"].to_numpy() * MONTH
    setcol(out, "xmpam", xmpam)
    setcol(out, "xmpot", np.maximum(df["HY130G"].to_numpy() * MONTH - xmpam, 0.0))
    setcol(out, "tad", df["HY145N"].to_numpy() * MONTH)
    setcol(out, "tis", df["HY140G"].to_numpy() * MONTH)
    setcol(out, "yds", df["HY020"].to_numpy() * MONTH)
    setcol(out, "xpp", pd.to_numeric(df["PY035G"], errors="coerce").fillna(0.0).to_numpy() * MONTH)
    setcol(out, "kfb", pd.to_numeric(df["PY020G"], errors="coerce").fillna(0.0).to_numpy() * MONTH)
    has_earn = ((pd.to_numeric(df["PY010G"], errors="coerce").fillna(0) > 0)
                | (pd.to_numeric(df["PY050G"], errors="coerce").fillna(0) > 0)).to_numpy()
    setcol(out, "loc", _loc(df["PL051A"], has_earn))
    setcol(out, "dec", _dec(df["PE021"], df["PE010"]))
    LOG.append("tpr<-HY120G (the ENFIA the model reads and passes through in 2023); "
               "yot<-HY110G split between members under 16; xhcrt<-HH060, xhcmomi<-HY100G, "
               "xhc<-HH070, xhcot<-xhc-xhcrt-xhcmomi; xmpam<-HY131G and xmpot<-HY130G-HY131G "
               "(was: the whole of HY130G into xmpam); tad<-HY145N, tis<-HY140G, yds<-HY020, "
               "xpp<-PY035G, kfb<-PY020G; loc<-PL051A; dec<-PE021/PE010")
    # ---- financial capital: IMPLEMENTED, MEASURED, AND NOT SHIPPED ----
    # The EL codebook publishes a consistent recipe, one rate stated once:
    #     afc = 0
    #     Interest rate (European source) = 0.00302
    #     replace afc= (yiy * 12) / (interest rate)
    # It was implemented as `afc = (yiy*12)/EL_INT_RATE` and put through what was then the
    # acceptance test for this class of derivation: does the minimum income aggregate move
    # TOWARDS what the scheme is published as spending. It moves AWAY. Measured: KEA falls
    # from EUR 497.7m to EUR 493.9m against the EUR 520m external for 2023 in Y16_CR_EL
    # table A3.6, so the gap widens from -4.3% to -5.0%.
    #
    # THAT TEST CANNOT DISCRIMINATE, and this was already visible here before it was acted
    # on. It could not have gone the other way: the Greek aggregate already sits BELOW the
    # published spend, and an asset test can only remove recipients, so any asset test at
    # all moves Greece further from the external figure. The measured move is what the
    # mechanism guarantees, not a verdict on the derivation. The same reasoning is why the
    # standing caveat was wrong in sign: the Greek minimum income is not overstated against
    # what the scheme spends, it is understated, EUR 520m is the target of the calibration
    # adjustment Greece runs and does not reach, and EUROMOD's own baseline (426m) is
    # further below the external than this build is. See DATA_ISSUES 9.9.
    #
    # THE GROUND THAT STANDS is about the input rather than the output. Greek investment
    # income is captured at 0.05 of the external figure in the same country report, against
    # 0.57 for Spain, whose afc IS shipped. Capitalising a series carrying a twentieth of
    # the income it should produces a stock that is wrong by construction, not merely
    # imprecise, and 1/r amplifies it. That is why the two countries were decided
    # differently on one recipe. The decision is unchanged; its grounds have been restated.
    #
    # The line is kept, commented, so that the decision is visible where the code is:
    #     setcol(out, "afc", out["yiy"].to_numpy() * 12.0 / EL_INT_RATE)
    LOG.append(f"afc NOT populated: the codebook recipe (yiy*12)/{EL_INT_RATE} was "
               "implemented and measured. It moves the KEA aggregate away from the published "
               "external spend (497.7 -> 493.9 against 520), but that test CANNOT "
               "DISCRIMINATE: the build already sits below 520 and an asset test only removes "
               "recipients, so any asset test whatever moves it further away. The ground it "
               "is held back on is the input: Greek yiy is captured at 0.05 of the external "
               "figure, against 0.57 for Spain, whose afc IS shipped")
    LOG.append("NOT POPULATED, and why: lochz needs em06, and its published fallback needs lin, which "
               "needs PL111A, shipped empty; drgn2 needs NUTS-2 and DB040 carries NUTS-1; "
               "amrar, amolv, lpm, lpmfr, ddita and every kb02_/eu02_/sb02_/oe02_ benefit "
               "component are national-SILC")

    setcol(out, "yemmy", np.where(yem > 0, months_work.to_numpy().clip(1, 12), 0))
    setcol(out, "ysemy", np.where(yse > 0, 12, 0))
    setcol(out, "bunctmy", np.where(unemp > 0,
           pd.to_numeric(df["PL085"], errors="coerce").fillna(0).clip(1, 12).to_numpy(), 0))
    wage = np.where(lhw > 0, (yem * 12.0) / np.maximum(lhw * 52.0, 1.0), 0.0)
    setcol(out, "yivwg", np.where(adult, np.maximum(wage, 7.0), 0.0))
    LOG.append("CEILING: yivwg Heckman wage proxied (yem/hours, floored 7); "
               "yemmy and bunctmy approximated from months variables; "
               "ysemy set to 12 for everyone with self-employment income, the defect "
               "DATA_ISSUES 9.13 describes for Spain, not corrected here")

    out = out.sort_values(["idhh", "idperson"]).reset_index(drop=True)
    # carry NUTS-1 (DB040) and idhh out-of-band for the per-unit layer / RWI join
    nuts1 = (df.sort_values(["idhh", "idperson"]).reset_index(drop=True)
             [["idhh", "nuts1"]].drop_duplicates("idhh"))
    return out, list(LOG), nuts1
