"""
convert_full.py -- FULL ES 2024 UDB -> EUROMOD input conversion.

Promotes the experiment converter to a proper build, following the official ES
Data Requirements Document (DRD) recipes shipped with the model. The four
experiment stubs are fixed:
  1. Benefits: the read pension, unemployment and market-income components are
     mapped from their SILC sources per the DRD, and the simulation drivers
     (marital status, education, labour-history months, family pointers) are
     built so the model can simulate the means-tested benefits (IMV minimum
     income, child benefit, housing) instead of defaulting them to 0.
  2. Net-to-gross: ES gross is directly grounded; the gross SILC components
     (PY...G, HY...G) are used as-is, divided by 12 (HX010 = 1.0 for euro ES).
  3. Intra-household allocation: household HY amounts (capital, rent, transfers)
     are allocated to the oldest household member per the EMC sharing rule, not
     dumped on the lowest-id head.
  4. Pointers and units: idmother/idfather/idpartner are built from
     RB220/RB230/RB240 (full person ids), and marital status from PB190, so the
     assessment and benefit units are constructed.

COMPLETED CONVERSION. Every input variable a live ES_2023 policy reads for
which the EUROMOD input data codebook publishes a recipe, and whose sources the public
user database carries, is now populated from that recipe. The inventory behind this is
generated by `europe/model/input_inventory.py`;
the recipes are quoted beside each assignment below. Two decision rules govern what is
NOT populated, and both come from the model rather than from us:

  * If a variable is a column of the dataset class we declare ourselves to be (the ES
    training template, which mirrors the b1 variable list), the class is expected to carry
    it, so a published recipe is implemented. `poa00`, `poacm`, `poanc`, `psuwd00`,
    `psuwdcm` and `psuot` are all such columns, which is why the pension aggregate is now
    decomposed rather than routed whole.
  * If it is not a column and `setdefault_es` supplies it, the model's own default stands.
    That is why `pdi00` is still the whole `PY130G`: `pdi00`, `pdicm` and `pdinc` are not
    columns of this class, and SetDefault sets `pdi00 = pdi` and the other two to zero.

ACCURACY CEILING. The EU-SILC data lacks the national-SILC variables and the full
employment/contribution history the official EUROMOD input carries. Consequently:
the contribution base for re-simulated contributory benefits (bunctpc) and the
Heckman-imputed wage (yivwg) are proxied, not reproduced; the child-benefit
disaggregation (`bch00`, `bchdi`) and the severance split (`ysv`) rest on theoretical
benefit amounts the codebook does not publish, so they are left at zero rather than
guessed; `lindi` cannot be built because `PL111A` ships empty; and the financial capital
stock `afc` is reported rather than derived. Each is logged.

DATA HANDLING: reads the EU-SILC data read-only; never writes converted microdata
to disk; returns the input DataFrame in memory for a single .run().
"""
import glob
import os

import numpy as np
import pandas as pd

# The licensed EU-SILC UDB. Held outside this tree, and outside the sibling
# LOCAL_ONLY, under the IGP data share. Set BENEFITS_SILC_ROOT to the folder holding the
# per-country _CROSS directories to run this anywhere else; the literal below is where it
# sits on the machine the surfaces were built on, kept as the recorded location rather
# than as an assumption about any other machine.
_SILC_ROOT = os.environ.get(
    "BENEFITS_SILC_ROOT",
    "")
UDB = os.path.join(_SILC_ROOT, "ES_CROSS", "2024")
if not os.path.isdir(UDB):
    raise SystemExit(
        "EU-SILC UDB not found at:\n  " + UDB + "\n"
        "Set BENEFITS_SILC_ROOT to the folder containing ES_CROSS/2024, which must hold\n"
        "UDB_cES24D.csv, UDB_cES24H.csv, UDB_cES24P.csv and UDB_cES24R.csv.\n"
        "The data is licensed and is not, and must not be, in this repository.")
MONTH = 1.0 / 12.0
# SILC PL032 (self-defined economic status, 2021+ coding) -> EUROMOD les, matching the
# EL converter (the structurally-verified reference). The prior {5:5,3:4,6:6} was
# miscoded against an older scheme and scrambled non-employed status for ~30,700
# persons.
#   PL032: 2 unemployed, 3 retired, 4 unable/ill, 5 student, 6 domestic, 7 other inactive
#   les:   2 self-emp, 3 employee, 4 sick/disabled, 5 unemployed, 6 retired, 7 inactive
PL032_NONEMP = {2: 5, 3: 6, 4: 4, 5: 7, 6: 7, 7: 7, 8: 4, 9: 1}
PB190_TO_DMS = {1: 1, 2: 2, 3: 3, 4: 5, 5: 4}  # SILC -> EUROMOD (5 = widowed, 4 = divorced)
HH021_TO_AMRTN = {1: 1, 2: 2, 3: 3, 4: 3, 5: 4}  # SILC tenure -> EUROMOD amrtn (EL reference)
# ISCO-08 two-digit (PL051A) -> EUROMOD loc, the codebook's own ES recipe, transcribed.
LOC_BANDS = [((1, 2, 3), 0), (range(11, 15), 1), (range(21, 27), 2), (range(31, 36), 3),
             (range(41, 45), 4), (range(51, 55), 5), (range(61, 64), 6),
             (range(71, 76), 7), (range(81, 84), 8), (range(91, 97), 9)]
# ES lcs: "replace lcs=1 if temp_occup in {1,2,3,11,23,34,54}", temp_occup = pl051a.
LCS_CODES = {1, 2, 3, 11, 23, 34, 54}
# The rate the ES codebook's own afc formula divides by. Its prose cites 0.57 per cent;
# its code divides by this. See the assignment for why the code wins and the prose stays
# on the record.
ES_AVIR = 0.002625

# conversion log (filled at runtime, returned alongside the frame)
LOG = []


def _file(letter):
    return glob.glob(os.path.join(UDB, f"UDB_c*{letter}.csv"))[0]


def _deh(pe041):
    v = pd.to_numeric(pe041, errors="coerce")
    out = np.where(v >= 500, 3, np.where(v >= 300, 2, 1)).astype("int64")
    out[np.isnan(v)] = 1
    return out


def _region(db040):
    s = db040.astype(str).str.replace("ES", "", regex=False)
    return pd.to_numeric(s, errors="coerce").fillna(0).astype("int64")


def _degurba(db100):
    """SILC DB100 (degree of urbanisation: 1 dense, 2 intermediate, 3 thin) ->
    EUROMOD drgur/drgmd/drgru (EL reference); default urban where unknown."""
    v = pd.to_numeric(db100, errors="coerce").fillna(1).to_numpy()
    drgur = (v == 1).astype("int64")
    drgmd = (v == 2).astype("int64")
    drgru = (v == 3).astype("int64")
    drgur[~np.isin(v, [1, 2, 3])] = 1
    return drgur, drgmd, drgru


def _loc(pl051a, has_earnings):
    """EUROMOD loc from ISCO-08 two-digit PL051A, the codebook's ES recipe.

    The recipe in full: the ten bands above, then `loc = -1 if py010 == 0 & py050 == 0`,
    then its own imputation, "missing are imputed with the occupation that has the highest
    proportion of workers", i.e. the mode among those with an occupation.
    """
    v = pd.to_numeric(pl051a, errors="coerce").to_numpy()
    out = np.full(len(v), np.nan)
    for codes, val in LOC_BANDS:
        out[np.isin(v, list(codes))] = val
    out[np.isnan(out) & ~has_earnings] = -1
    known = out[(~np.isnan(out)) & (out >= 0)]
    mode = int(pd.Series(known).mode().iloc[0]) if len(known) else 5
    out[np.isnan(out)] = mode                      # the recipe's own mode imputation
    return out.astype("int64"), mode


def _dec(pe021, pe010, rx010, pe041):
    """EUROMOD dec (current education) from the codebook's ES recipe.

    Transcribed as published, with one substitution recorded on its face: the over-16
    branch names `pe040`, the highest ISCED level attained, which the 2024 release carries
    as `PE041`. That is a wave renaming of the same variable, not a different one, and it
    is the only place this conversion reads a field under a name the recipe does not use.
    """
    e21 = pd.to_numeric(pe021, errors="coerce").to_numpy()
    e10 = pd.to_numeric(pe010, errors="coerce").to_numpy()
    age = pd.to_numeric(rx010, errors="coerce").to_numpy()
    e41 = pd.to_numeric(pe041, errors="coerce").to_numpy()
    d = np.full(len(e21), np.nan)
    d[e21 == 0] = 1
    d[e21 == 10] = 2
    d[e21 == 20] = 3
    d[(e21 >= 30) & (e21 <= 39)] = 4
    d[(e21 >= 40) & (e21 <= 49)] = 5
    d[(e21 >= 50) & (e21 <= 80)] = 6
    d[e10 == 2] = 0
    m = np.isnan(d)
    d[m & (age <= 5)] = 1
    d[m & (age > 5) & (age <= 11)] = 2
    d[m & (age > 11) & (age <= 14)] = 3
    d[m & (age > 14) & (age < 16)] = 4
    m = np.isnan(d)
    inschool = (e10 == 1)
    d[m & inschool & (age >= 16) & (e41 < 500)] = (e41[m & inschool & (age >= 16)
                                                       & (e41 < 500)] // 100) + 2
    d[np.isnan(d) & inschool & (age > 16) & (e41 >= 500)] = 6
    d[np.isnan(d)] = 0
    return np.clip(d, 0, 6).astype("int64")


def convert_es_2024_full(template_cols):
    LOG.clear()
    D = pd.read_csv(_file("D"), usecols=["DB030", "DB090", "DB040", "DB100"])
    R = pd.read_csv(_file("R"), usecols=["RB030", "RX030", "RX020", "RB090",
                                         "RB220", "RB230", "RB240", "RX010"])
    P = pd.read_csv(_file("P"), usecols=[
        "PB030", "PB190", "PE010", "PE021", "PE041", "PL032", "PL040A", "PL051A", "PL060",
        "PL073", "PL074", "PL075", "PL076", "PL200", "PL085",
        "PY010G", "PY020G", "PY030G", "PY035G", "PY050G", "PY080G", "PY090G",
        "PY092G", "PY093G", "PY100G", "PY101G", "PY102G", "PY103G",
        "PY110G", "PY111G", "PY112G", "PY120G", "PY130G", "PY140G"])
    H = pd.read_csv(_file("H"), usecols=["HB030", "HX010", "HY020", "HY040G", "HY050G",
                                         "HY053G", "HY060G", "HY070G", "HY080G", "HY090G",
                                         "HY100G", "HY110G", "HY130G", "HY140G", "HY145N",
                                         "HH021", "HH060", "HH070", "HH071"])

    df = R.rename(columns={"RB030": "idperson", "RX030": "idhh",
                           "RX020": "dag", "RB090": "sex"})
    df = df.merge(D.rename(columns={"DB030": "idhh", "DB090": "dwt", "DB040": "region",
                                    "DB100": "degurba"}),
                  on="idhh", how="left")
    df = df.merge(P.rename(columns={"PB030": "idperson"}), on="idperson", how="left")
    n = len(df)

    # household capital/rent/transfers allocated to the OLDEST member (EMC rule)
    df = df.merge(H.rename(columns={"HB030": "idhh"}), on="idhh", how="left")
    oldest = df.groupby("idhh")["dag"].transform("max")
    is_oldest = (df["dag"] == oldest) & (~df.duplicated(["idhh", "dag"]) | (df["dag"] == oldest))
    # ensure exactly one recipient per household (first oldest)
    first_oldest = df.assign(_o=(df["dag"] == oldest)).sort_values(["idhh", "_o", "idperson"],
                                                                   ascending=[True, False, True])
    recip = first_oldest.groupby("idhh").head(1).index
    is_recip = np.zeros(n, dtype=bool); is_recip[df.index.get_indexer(recip)] = True
    # monetary household amounts to the oldest member; HH021 (tenure) is a household
    # attribute kept on every member, not allocated.
    #
    # ALLOCATION SUBSTITUTION, stated once and applying to every household amount below.
    # The codebook allocates household money either to "the default income recipients (the
    # household respondent and their partner)" or to "the people responsible for the
    # accommodation", the latter as `int_resp / int_respno`. The public user database
    # identifies neither: HB080 and HB090, the persons responsible for the accommodation,
    # are not in the release. The whole household amount therefore goes to the oldest
    # member, the EMC sharing rule this converter already used for capital and rent. The
    # household total is exact; only its allocation within the household is a substitution,
    # and every EUROMOD aggregate this build reports is a household or population total.
    HH_MONEY = ("HY040G", "HY050G", "HY053G", "HY060G", "HY070G", "HY080G", "HY090G",
                "HY100G", "HY130G", "HY140G", "HY145N", "HY020", "HH060", "HH070", "HH071")
    for c in HH_MONEY:
        df[c] = np.where(is_recip, pd.to_numeric(df[c], errors="coerce").fillna(0.0), 0.0)

    out = pd.DataFrame(0.0, index=np.arange(n), columns=list(template_cols))

    # ---- identifiers and pointers ----
    out["idperson"] = df["idperson"].to_numpy("int64")
    out["idhh"] = df["idhh"].to_numpy("int64")
    for src, dst in (("RB220", "idfather"), ("RB230", "idmother"), ("RB240", "idpartner")):
        v = pd.to_numeric(df[src], errors="coerce").fillna(0)
        out[dst] = np.where(v > 0, v, 0).astype("int64")
    LOG.append("pointers idfather/idmother/idpartner <- RB220/RB230/RB240 (full ids)")

    # ---- demographics ----
    out["dag"] = df["dag"].fillna(0).clip(lower=0).to_numpy("int64")
    out["dgn"] = np.where(df["sex"].to_numpy() == 1, 1, 0)
    dms = df["PB190"].map(PB190_TO_DMS)
    out["dms"] = dms.where(df["dag"] >= 16, 1).fillna(1).to_numpy("int64")
    out["ddi"] = (df["PY130G"].fillna(0) > 0).astype("int64").to_numpy()
    out["deh"] = _deh(df["PE041"])
    # occupation, civil-servant flag, and current education, each the codebook's own ES
    # recipe. loc is what prelim_es reads to choose the contribution-base group, and
    # without it every employee falls into the residual "loc != 1 & loc != 2" branch.
    has_earn = (pd.to_numeric(df["PY010G"], errors="coerce").fillna(0) > 0) | \
               (pd.to_numeric(df["PY050G"], errors="coerce").fillna(0) > 0)
    loc, loc_mode = _loc(df["PL051A"], has_earn.to_numpy())
    out["loc"] = loc
    out["lcs"] = pd.to_numeric(df["PL051A"], errors="coerce").isin(LCS_CODES) \
        .astype("int64").to_numpy()
    out["dec"] = _dec(df["PE021"], df["PE010"], df["RX010"], df["PE041"])
    LOG.append(f"loc<-PL051A (ISCO-2digit -> 1-digit, codebook ES recipe; missing imputed "
               f"at the mode, which is {loc_mode}); lcs<-PL051A in {{1,2,3,11,23,34,54}}; "
               "dec<-PE021/PE010/RX010, the over-16 branch reading PE041 where the recipe "
               "names PE040 (the same variable under its 2021+ name)")
    out["drgn2"] = _region(df["region"]).to_numpy()
    drgur, drgmd, drgru = _degurba(df["degurba"])      # from DB100 (was hardcoded 1)
    out["drgur"] = drgur
    if "drgmd" in out.columns:
        out["drgmd"] = drgmd
    if "drgru" in out.columns:
        out["drgru"] = drgru
    out["amrtn"] = df["HH021"].map(HH021_TO_AMRTN).fillna(3).to_numpy("int64")  # from HH021 (was hardcoded 3)
    out["dwt"] = df["dwt"].fillna(0.0).to_numpy()
    LOG.append("dms<-PB190; ddi<-(PY130G>0); deh<-PE041(ISCED->1/2/3); drgn2<-DB040; "
               "drgur/drgmd/drgru<-DB100; amrtn<-HH021")

    # ---- labour ----
    adult = (df["dag"] >= 16).to_numpy()
    pl040 = df["PL040A"]
    les = np.zeros(n, dtype="int64")
    les[adult & pl040.isin([1, 2, 4]).to_numpy()] = 2
    les[adult & (pl040 == 3).to_numpy()] = 3
    nonemp = adult & (les == 0)
    inferred = df["PL032"].map(PL032_NONEMP).fillna(7).to_numpy().astype("int64")
    les[nonemp] = inferred[nonemp]
    out["les"] = les
    lhw = df["PL060"].fillna(0).to_numpy(float)
    lhw = np.where((les == 3) & (lhw <= 0), 38.0, lhw)  # default hours for employees w/o hours
    out["lhw"] = lhw
    months_work = df[["PL073", "PL074", "PL075", "PL076"]].fillna(0).sum(axis=1).clip(0, 12)
    out["liwmy"] = months_work.to_numpy()
    out["liwwh"] = (df["PL200"].fillna(0) * 12).clip(lower=0).to_numpy()
    out["lunmy"] = df["PL085"].fillna(0).clip(0, 12).to_numpy()
    LOG.append("liwmy<-sum(PL073..076); liwwh<-PL200*12; lunmy<-PL085 (work-history drivers)")

    # ---- market incomes (gross, monthly) ----
    out["yem"] = df["PY010G"].fillna(0.0).to_numpy() * MONTH
    out["yse"] = df["PY050G"].fillna(0.0).to_numpy() * MONTH
    out["ypp"] = df["PY080G"].fillna(0.0).to_numpy() * MONTH
    out["yiy"] = df["HY090G"].fillna(0.0).to_numpy() * MONTH      # interest/dividends (oldest)
    out["ypr"] = df["HY040G"].fillna(0.0).to_numpy() * MONTH      # rent (oldest)
    out["ypt"] = df["HY080G"].fillna(0.0).to_numpy() * MONTH      # inter-hh transfers (oldest)
    if "xmp" in out.columns:
        out["xmp"] = df["HY130G"].fillna(0.0).to_numpy() * MONTH  # maintenance/transfers paid (oldest)
    LOG.append("market: yem<-PY010G, yse<-PY050G, ypp<-PY080G, yiy<-HY090G, ypr<-HY040G, "
               "ypt<-HY080G, xmp<-HY130G (maintenance paid) (/12)")

    # ---- pensions (gross, monthly), decomposed as the codebook decomposes them ----
    # A SILC aggregate is not its contributory component. The codebook is explicit that
    # they are not the same thing:
    #   poa00 = py102g/12*hx010     old-age CONTRIBUTORY
    #   poacm = py101g/12*hx010     complement to the minimum ("complemento a minimos")
    #   poanc = py103g/12*hx010     old-age NON-contributory
    #   poa   = poa00 + poacm + poanc
    #   psuwd00 = (py112g/12) if py112g > 0 & dms == 5     widow(er)s only
    #   psuwdcm = py111g/12                                 survivor complement
    #   psuot   = psu - psuwdcm - psuwd00                   the residual
    #   psu     = py110g/12*hx010
    # The identities hold to the euro in the 2024 release: PY100G = PY101G+PY102G+PY103G
    # and PY110G = PY111G+PY112G, checked before this was written. All six components are
    # columns of this dataset class, so the class is expected to carry them decomposed and
    # setdefault_es does not cover them.
    #
    # DISABILITY IS THE EXCEPTION AND IS DELIBERATE. pdi00, pdicm and pdinc are NOT columns
    # of this class, and setdefault_es sets `pdi00 = pdi` and zeroes the other two. The
    # model's own default for a dataset like ours therefore puts the whole aggregate in
    # pdi00, which is what this converter supplies. Splitting it on py132g/py131g/py133g
    # would move money into two components the model has already decided are zero here.
    poa100 = pd.to_numeric(df["PY100G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    out["poa"] = poa100
    out["poa00"] = pd.to_numeric(df["PY102G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    out["poacm"] = pd.to_numeric(df["PY101G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    out["poanc"] = pd.to_numeric(df["PY103G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    psu = pd.to_numeric(df["PY110G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    psuwdcm = pd.to_numeric(df["PY111G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    py112 = pd.to_numeric(df["PY112G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    psuwd00 = np.where((py112 > 0) & (out["dms"].to_numpy() == 5), py112, 0.0)
    out["psu"] = psu
    out["psuwdcm"] = psuwdcm
    out["psuwd00"] = psuwd00
    out["psuot"] = np.maximum(psu - psuwdcm - psuwd00, 0.0)
    disab = pd.to_numeric(df["PY130G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    out["pdi00"] = disab; out["pdi"] = disab
    LOG.append("pensions DECOMPOSED per codebook: poa00<-PY102G (contributory), "
               "poacm<-PY101G (complement), poanc<-PY103G (non-contributory), poa<-PY100G; "
               "psuwd00<-PY112G where dms=5, psuwdcm<-PY111G, psuot<-psu-psuwdcm-psuwd00, "
               "psu<-PY110G; pdi00=pdi<-PY130G whole, following setdefault_es for this "
               "dataset class (pdi00/pdicm/pdinc are not columns of it)")

    # ---- unemployment, split as the codebook splits it ----
    # bunct = py092g/12 (insurance), bunnc = py093g/12 (assistance), bun = bunct+bunnc+bunot,
    # and PY090G = PY092G + PY093G exactly in this release, so the aggregate is unchanged
    # and only the split is new. bunot is zero by setdefault_es on this dataset class, so
    # the assistance component is whole rather than a share of an unpublished split.
    # ysv, the severance payment the codebook carves out of py092g where the observed
    # benefit exceeds the theoretical maximum insurance benefit, stays at zero: that
    # theoretical maximum is not published, and choosing one would be inventing it.
    unemp = pd.to_numeric(df["PY090G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    out["bun"] = unemp
    out["bunct"] = pd.to_numeric(df["PY092G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    out["bunnc"] = pd.to_numeric(df["PY093G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    LOG.append("unemployment SPLIT per codebook: bunct<-PY092G, bunnc<-PY093G, bun<-PY090G "
               "(= the sum, exactly, in this release); ysv left 0, its theoretical maximum "
               "benefit is not published")

    # ---- read benefits the model does not simulate on this base ----
    # bhl = py120g/12*hx010; bed = py140g/12*hx010; bho = hy070g/12*hx010;
    # bfa = hy050g/12*hx010; bsa = hy060g/12*hx010; bchot = t_bfancmt/12*hx010 with
    # t_bfancmt = hy053g; bch = bch00 + bchdi + bchot.
    # bhl and bed and bho enter ils_bennt/ils_benmt directly. bfa and bsa are read only as
    # drivers (bunmt_es and the uprating list), and no income list adds them, so feeding
    # them cannot double-count the simulated means-tested benefits. bch00 and bchdi need a
    # theoretical child benefit the codebook does not publish, so they stay zero and bch is
    # therefore bchot.
    out["bhl"] = pd.to_numeric(df["PY120G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    out["bed"] = pd.to_numeric(df["PY140G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    out["bho"] = df["HY070G"].to_numpy() * MONTH
    out["bfa"] = df["HY050G"].to_numpy() * MONTH
    out["bsa"] = df["HY060G"].to_numpy() * MONTH
    out["bchot"] = df["HY053G"].to_numpy() * MONTH
    out["bch"] = out["bchot"].to_numpy()
    LOG.append("read benefits: bhl<-PY120G, bed<-PY140G, bho<-HY070G, bfa<-HY050G, "
               "bsa<-HY060G, bchot<-HY053G, bch=bchot (bch00/bchdi need an unpublished "
               "theoretical amount)")

    # ---- other income, housing costs, and the survey tax and disposable lines ----
    # yot = (hy110g/12*hx010) / totchild * (child == 1), the codebook's own split between
    # the household's members under 16.
    child = (df["dag"].fillna(0) < 16).to_numpy()
    totchild = pd.Series(child.astype(float)).groupby(df["idhh"].to_numpy()).transform("sum")
    hy110 = pd.to_numeric(df["HY110G"], errors="coerce").fillna(0.0)
    hy110_hh = hy110.groupby(df["idhh"].to_numpy()).transform("max").to_numpy()
    with np.errstate(invalid="ignore", divide="ignore"):
        yot = np.where(child & (totchild.to_numpy() > 0),
                       hy110_hh / np.maximum(totchild.to_numpy(), 1.0) * MONTH, 0.0)
    out["yot"] = yot
    xhcrt = df["HH060"].to_numpy()                       # hh060 * hx010, monthly as held
    xhcmomi = df["HY100G"].to_numpy() * MONTH
    xhcmomc = df["HH071"].to_numpy()
    xhc = np.maximum(df["HH070"].to_numpy(), xhcrt + xhcmomi)   # the recipe's own floor
    out["xhcrt"] = xhcrt
    out["xhcmomi"] = xhcmomi
    out["xhcmomc"] = xhcmomc
    out["xhc"] = xhc
    out["xhcot"] = np.maximum(xhc - xhcrt - xhcmomi, 0.0)
    out["xpp"] = pd.to_numeric(df["PY035G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    out["kfb"] = pd.to_numeric(df["PY020G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    LOG.append("yot<-HY110G split between household members under 16 (codebook rule); "
               "xhcrt<-HH060, xhcmomi<-HY100G, xhcmomc<-HH071, xhc<-HH070 floored at "
               "xhcrt+xhcmomi, xhcot<-xhc-xhcrt-xhcmomi; xpp<-PY035G; kfb<-PY020G")
    # Variables the b1 class declares and the training template omits. They were supplied
    # as zero columns to clear the not-found warnings; each now carries its published
    # value. None of them enters an income list: tad, tis, yds and tscer are read by the
    # uprating list and by the UDB comparison list only, and the employer contribution the
    # model reports is the simulated tscer_s, not this.
    out["tad"] = df["HY145N"].to_numpy() * MONTH
    out["tis"] = df["HY140G"].to_numpy() * MONTH
    out["yds"] = df["HY020"].to_numpy() * MONTH
    out["tscer"] = pd.to_numeric(df["PY030G"], errors="coerce").fillna(0.0).to_numpy() * MONTH
    LOG.append("tad<-HY145N, tis<-HY140G, yds<-HY020, tscer<-PY030G (survey lines, read by "
               "the uprating and UDB comparison lists only)")

    # ---- financial capital, the codebook's own recipe ----
    # ES codebook, verbatim:
    #     local avir = 0.002625
    #     gen afc = 0
    #     replace afc = (yiy * 12) / `avir'
    # THE CODEBOOK ENTRY IS INTERNALLY INCONSISTENT AND IS NOT RESOLVED HERE. The prose
    # beside the formula cites "Bank interest rates - deposits from households with an
    # agreed maturity of over two years - Spain", ECB series
    # 124.MIR.M.ES.B.L22.H.R.A.2250.EUR.O, "Arithmetic average of 2018 monthly values
    # (2018: 0.57%)". The code divides by 0.002625, which is 0.2625 per cent, not 0.57.
    # The two differ by a factor of 2.2 and nothing in the entry says which the EMSD used.
    # The FORMULA's rate is the one implemented, because the formula is the recipe; the
    # prose figure is recorded here and in the technical report rather than silently
    # preferred. The stock scales as 1/rate, so this choice is the whole answer, and the
    # sensitivity across the plausible range is reported beside the caveat.
    afc = out["yiy"].to_numpy() * 12.0 / ES_AVIR
    out["afc"] = afc
    LOG.append(f"afc<-(yiy*12)/{ES_AVIR} (codebook ES formula). NOTE: the same codebook "
               f"entry's prose cites 0.57% where its code divides by 0.2625%; the formula's "
               f"rate is used and the inconsistency is recorded, not resolved")
    LOG.append("afc IS SHIPPED, and the grounds are not the aggregate. The IMV outlay is the object of the Benefit Calibration Adjustment, which is on for ES_2023 on this dataset and aims it at the EUR 2,504m the scheme is published as spending, so the aggregate is not evidence about the eligibility rules whichever way it lands. (It does not land ON that figure: it lands 0.99 per cent under, at EUR 2,479.3m, and `benefit_adjustments.json` carries `target_binds: false`. The adjustment's take rule accumulates while the weighted total stays at or below the target, so landing under it is what binding looks like, and the aggregate is not evidence either way.) What stands: (1) the recipe is published in the codebook FOR SPAIN, so it is the model's own rule, not a convention of ours; (2) zero is the MORE extreme assumption, since afc=(yiy*12)/r makes afc=0 the implication of an infinite return on capital. A live asset test moves WHO is paid, not how much in total")
    LOG.append("NOT POPULATED, and why: lindi cannot be built, PL111A ships empty in this "
               "release; bch00/bchdi/ysv/bunncmy each need a theoretical amount the codebook "
               "does not publish")

    # ---- months-receiving and proxies (accuracy ceiling) ----
    # Both months-of-receipt variables read the SAME months-worked count, on the same
    # clip. A bare 12 for everyone with self-employment income would mean
    # income, while yemmy on the line above already used months_work; the months
    # variable was present, populated, and used one line up. Self-employed
    # contributions scale directly with ysemy. On this clip the 5,721 records with
    # self-employment income mean 9.853 months, and 22.4 per cent are below a full year,
    # so charging twelve months to all of them would charge a full year of contributions
    # to people the survey records as having worked less than one. Contributions read
    # EUR 17,238.9m against a published EUR 14,551m, +18.5%, and the residual is
    # unexplained (DATA_ISSUES 9.13). This is a transcription of the employee line, not a
    # new derivation.
    out["yemmy"] = np.where(out["yem"].to_numpy() > 0, months_work.to_numpy().clip(1, 12), 0)
    out["ysemy"] = np.where(out["yse"].to_numpy() > 0, months_work.to_numpy().clip(1, 12), 0)
    out["bunctmy"] = np.where(out["bunct"].to_numpy() > 0, df["PL085"].fillna(0).clip(1, 12).to_numpy(), 0)
    # Heckman wage proxy, floored positive to avoid div-by-zero in contributions
    wage = np.where(lhw > 0, (out["yem"].to_numpy() * 12.0) / np.maximum(lhw * 52.0, 1.0), 0.0)
    out["yivwg"] = np.where(adult, np.maximum(wage, 7.0), 0.0)
    out["bunctpc"] = out["yem"].to_numpy()  # contribution-base proxy = current earnings
    LOG.append("CEILING: yivwg Heckman wage proxied (yem/hours, floored 7); bunctpc proxied = yem; "
               "yemmy/ysemy/bunctmy approximated from months variables. ysemy reads "
               "months_work.clip(1,12), the same count on the same clip as yemmy one line "
               "above, so the 22.4 per cent of the self-employed the survey records as "
               "working less than a full year are charged for the months they worked")
    LOG.append("CEILING: the child-benefit disaggregation and the severance split rest on "
               "theoretical benefit amounts the codebook does not publish, so bch00, bchdi "
               "and ysv stay at zero")
    LOG.append("LEFT TO SIMULATION (input 0): IMV minimum income (bsa00) and the simulated "
               "minimum-pension complements poacm_s/poanc_s/psuwdcm_s, which the model "
               "computes from the read drivers now supplied")

    out = out.sort_values(["idhh", "idperson"]).reset_index(drop=True)
    return out, list(LOG)
