#!/usr/bin/env python3
"""Write europe/docs/VALUATION_CHAINS.md: how every provider outcome value is built.

Why this exists. The DATA_OUTCOMES sheet of `uk/tools/_superseded/valuation_tool.xlsx`
carries the arithmetic behind the twenty-one United Kingdom outcome values, and that
path is gitignored: the file is untracked and does not travel with the export. The
technical report says every figure is traceable to a source, so the derivation has to
be in the repository rather than in a workbook the reader does not receive.

Committing the workbook was considered and rejected. Four reasons, in order of weight:

  1. It does not reproduce the shipped values. The valuation stages set every multiplier
     it carries, so publishing it would publish a contradiction.
  2. It is a binary. The export excludes `.xlsx` from both the scrub and the
     forbidden-reference scan by suffix, so nothing inside it can be checked before it
     ships.
  3. It is a superseded TOOL, not a record: seventeen sheets, charts and images, of which
     one sheet is the derivation. Committing a whole second implementation to preserve one
     sheet is the wrong unit.
  4. A transcription is checkable and the workbook is not. The chain this file prints is
     parsed out of each parameter's own note with the same regexes `audit_provider_params.py`
     uses at 7.10d, and recomputed against the shipped value on every run, so this document
     cannot drift from the tools without 7.10d failing first.

Read-only apart from its own output. No microdata, no engine, no network.

  py -3 europe/model/write_valuation_chains.py
"""
import importlib.util
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
MACH = os.path.join(ROOT, "europe", "tool_machinery")
OUT = os.path.join(ROOT, "europe", "docs", "VALUATION_CHAINS.md")

spec = importlib.util.spec_from_file_location(
    "apap", os.path.join(ROOT, "audit_provider_params.py"))
apap = importlib.util.module_from_spec(spec)
spec.loader.exec_module(apap)

COUNTRIES = [("UK", "country_uk.json"), ("ES", "country_es.json"),
             ("IT", "country_it.json"), ("EL", "country_el.json")]
CUR = {"UK": "GBP", "ES": "EUR", "IT": "EUR", "EL": "EUR"}


def main():
    lines = [
        "# How every provider outcome value is built",
        "",
        "Generated by `europe/model/write_valuation_chains.py`. **Do not edit by hand.**",
        "",
        "Every value on the Provider tab of every tool is",
        "",
        "    raw x effect share x attribution",
        "",
        "and every value whose note carries an ORIGIN clause has all three printed below",
        "beside the value it produces. Two chains are therefore not shown: the Spanish and",
        "Italian drug and alcohol treatment values, whose notes give their origin and factor",
        "in prose rather than in an ORIGIN clause. Both are documented in",
        "[`PROVIDER_TOOLREADY_2024.md`](PROVIDER_TOOLREADY_2024.md).",
        "The chain is read out of each parameter's own note and recomputed here, with the",
        "same code `audit_provider_params.py` runs at check 7.10d, so this document cannot",
        "disagree with the tools without that check failing first.",
        "",
        "**The stage rule.** Where the effect share is already an impact net of a comparison",
        "group the attribution is 1.0, because the counterfactual is inside the number and",
        "deducting it a second time understates the value. Where the effect share is an",
        "observed outcome rate, the attribution is what removes the counterfactual. Where no",
        "source exists the value is declared an assumption and its note says so.",
        "",
        "`effect` and `attribution` read 1 on rows that take no stage.",
        "",
    ]
    total = fails = 0
    for cc, fn in COUNTRIES:
        block = json.load(io.open(os.path.join(MACH, fn), encoding="utf-8"))
        svcs = block["data"]["services"]
        lines += ["## %s" % cc, "",
                  "| service | point | raw (origin) | x factor | x effect | x attribution "
                  "| = shipped (%s) | reproduces |" % CUR[cc],
                  "|---|---|---:|---:|---:|---:|---:|---|"]
        for i, (name, o) in enumerate(block["data"]["outcomes"].items()):
            if not isinstance(o, dict):
                continue
            label = svcs[i]["name"] if i < len(svcs) else name
            rws, f = apap.outcome_rows_scoped(cc, label, o)
            fails += f
            for r in rws:
                if r["field"] in ("-",) or r["origin"] == "-":
                    continue
                total += 1
                lines.append("| %s | %s | %s | %s | %s | %s | %s | %s |" % (
                    label, r["field"], r["origin"], r["factor"],
                    r.get("effect", 1), r.get("attribution", 1), r["shipped"],
                    "yes" if r["verdict"] is True else r["verdict"]))
        lines.append("")
    lines += ["## Result", "",
              "**%d points recomputed from their own notes, %s.**"
              % (total, "none failing" if not fails else "**%d FAILING**" % fails),
              "",
              "`uk/tools/_superseded/valuation_tool.xlsx` is gitignored, does not travel, and does",
              "not reproduce the shipped values. This file is the record. The reasoning is",
              "in the header of the script that writes this one.",
              ""]
    io.open(OUT, "w", encoding="utf-8", newline="").write("\n".join(lines))
    print("wrote %s: %d points, %d failing" % (OUT, total, fails))
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
