"""write_conversion_record.py -- the record the technical report needs: for every input
variable the conversion populates, the source field it came from and the recipe used.

Runs each converter (no engine, no simulation), takes its own log, and lists every column
it leaves non-zero with the weighted annual total that column carries. The log lines are
the converters' own words, so this document cannot drift from what the code does without
the code changing.

Data-free: counts and population totals only.
"""
import importlib
import os
import sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
EUROPE = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(EUROPE, "common"))
for _d, _s in (("Spain", "es_real"), ("Italy", "it_real"), ("Greece", "el_real")):
    sys.path.insert(0, os.path.join(EUROPE, _d, "model", _s))
os.environ.setdefault("BENEFITS_ENGINE_QUIET", "1")
import engine  # noqa: E402

CC = {"ES": ("Spain", "ES_training_data", "convert_full", "convert_es_2024_full"),
      "IT": ("Italy", "IT_training_data", "convert_it", "convert_it_2024_full"),
      "EL": ("Greece", "EL_training_data", "convert_el", "convert_el_2024_full")}
MONETARY_HINT = ("y", "b", "p", "t", "x", "k")   # EUROMOD acronym first letters


def main():
    mod = engine.load_model()
    L = ["# What each conversion populates, and from where", "",
         "Generated by `europe/model/write_conversion_record.py`. For each country: the "
         "converter's own log, which names the source field and the recipe for every "
         "assignment, and then every column the converted frame leaves non-zero with the "
         "weighted annual total it carries. No engine run is involved and no microdata is "
         "reproduced.", "",
         "Each recipe is named in the converter's own log below, with the source field it "
         "reads and the group the variable falls in.", "",
         "## The two values in these conversions that are conventions of ours", "",
         "Everything else here implements a recipe the EUROMOD input data codebook "
         "publishes for that country. Two do not, and they are set out here rather than "
         "left to be inferred from a comment.", "",
         "**Italy's contract class, `lcl`.** The mapping used is ISCO-08 major groups 6 to "
         "9 to blue collar and 0 to 5 to white, over everyone with employment income, with "
         "EUROMOD's own `SetDefault_it` default of blue where no occupation is recorded. "
         "**No published EUROMOD rule licenses this.** Only Austria and Italy define `lcl` "
         "at all and both derive it from a national variable; Italy's documented "
         "construction uses `posdip`, the occupational-position variable, which the public "
         "release does not carry. What the substitution costs is compositional: the proxy "
         "puts 22.1 per cent of employees in blue collar by headcount and 23.0 per cent of "
         "the earnings base, against a national share nearer half, and because sickness and "
         "maternity is the only rate that differs between the two classes (2.68 against "
         "0.46 per cent) the whole of that error lands on one component. The bounds the "
         "class can produce at all are **EUR 177,906m if every employee is white collar and "
         "EUR 191,133m if every one is blue**, measured on the same input by "
         "`europe/model/collar_bounds.py`. The convention gives EUR 181,054m. The argument "
         "for it is that it is checked rather than that it is principled: it lands within 1 "
         "per cent of EUROMOD's own published baseline of EUR 179,797m (Y16_CR_IT table "
         "A3.4) and within 1 per cent of the EUR 180,821m of employer contributions EU-SILC "
         "records in PY030G, neither of which was used to construct it, and the published "
         "baseline lies between the two bounds.", "",
         "**Italy's second-property cadastral income, `aobiv`.** Not a codebook recipe "
         "either, but a statutory inversion rather than a convention: `aobiv = HY120G / "
         "rate / (1.05*160)`, where the 5 per cent revaluation and the coefficient of 160 "
         "are in the model itself and the only free parameter is the municipal IMU rate, "
         "confined by statute to 0.76 to 1.06 per cent. At the standard rate it gives "
         "EUR 9,784m against the EUR 9,245m the country report publishes for `aobiv`, and "
         "the published figure sits inside the statutory band.", ""]
    for cc, (name, train, modname, fn) in CC.items():
        template = list(mod.countries[cc].load_data(train).columns)
        conv = importlib.import_module(modname)
        res = getattr(conv, fn)(template)
        real, log = res[0], res[1]
        w = real["dwt"].to_numpy(float)
        rows = []
        for c in sorted(real.columns):
            v = pd.to_numeric(real[c], errors="coerce").fillna(0.0).to_numpy()
            if not np.any(v != 0):
                continue
            rows.append((c, int((v != 0).sum()), float((v * w).sum()) * 12 / 1e6,
                         len(np.unique(v))))
        L += [f"## {name} ({cc})", "",
              f"**{len(rows)} populated columns** of {real.shape[1]} in the input frame, "
              f"over {real.shape[0]:,} person records.", "",
              "### The converter's own log", ""]
        L += [f"* {line}" for line in log]
        L += ["", "### Every populated column", "",
              "| column | rows non-zero | weighted annual total | distinct values |",
              "|---|---:|---:|---:|"]
        for c, nz, tot, nd in rows:
            money = c[0] in MONETARY_HINT and nd > 12
            L.append(f"| `{c}` | {nz:,} | {tot:,.1f}{' EUR m' if money else ''} | {nd:,} |")
        L.append("")
    path = os.path.join(EUROPE, "docs", "CONVERSION_RECORD.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print("written", path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
